{% set name = "sphinx-nbexamples" %}
{% set version = "0.2.0" %}
{% set sha256 = "96d523e24c298f1a3a5b1583e685d463d3f96a1b8ec33321d1e69d8b144cf929" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - sphinx
    - ipython
    - nbconvert
    - pillow
    - jupyter_client
    - ipykernel
    - six
    - pandoc

test:
  imports:
    - sphinx_nbexamples

about:
  home: https://github.com/Chilipp/sphinx-nbexamples
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Create an examples gallery with sphinx from Jupyter Notebooks'

  description: |
    This module creates an example gallery for your documentation out of a
    bunch of jupyter notebooks using nbconvert.
  doc_url: http://sphinx-nbexamples.readthedocs.io/
  dev_url: https://github.com/Chilipp/sphinx-nbexamples

extra:
  recipe-maintainers:
    - Chilipp
